name: Test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  tests:

    runs-on: ubuntu-latest
    services:
      db:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABSE: testname
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
          options: >-
            --health-cmd "mysqladmin ping"
            --health-interval 10s
            --healtth-timeout 5s
            --health-retries 5

    steps:
    - uses: actions/checkout@master

    - name: Setup Golang
      uses: actions/setup-go@v2

    - name: Apply linter
      uses: golangci/golangci-lint-action@v2
      with:
        skip-go-installation: true

    - name: Build
      run: make all

    - name: setup mysql
      run: mysql -u root -proot< setup.test.sql

    - name: Run tests
      run: make test
