name: Test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup Golang
      uses: actions/setup-go@v2

    - name: Apply linter
      uses: golangci/golangci-lint-action@v2
      with:
        skip-go-installation: true

    - name: Build
      run: make all

    - name: Run tests
      run: make test
